### ISSUE TITLE
A drop in memory values is observed in monitor_proc results

### ISSUE THREAD

**Issue by rraminen** [seemethere/dotfiles#1]
Among the results of the monitor_proc on any application, a drop in the memory values (in the columns Max RSS Mem. and Max PSS Mem.) is observed at many places. According to the monitor_proc code, should it not be in an increasing order as we print the largest of the current value and previous value in each iteration?

The output of the monitor_proc on imagenet application:
![image](https://user-images.githubusercontent.com/62723901/84424161-4b746080-abe5-11ea-8915-87342939869e.png)

cc @jithunnair-amd

**Comment by jithunnair-amd** [comment]
Actually, the drop is observed even in the "Max GPU Mem" column as evident above.

**Comment by seemethere** [comment]
I noticed this as well.

I couldn't actually figure out why this had happened and actually would just grep the results of `monitor_proc` and then take the highest value from there.

The script itself isn't perfect and I'd be open to contributions to make it better if possible.

**Comment by rraminen** [comment]
This PR has a fix for this issue: https://github.com/seemethere/dotfiles/pull/4 
Please let me know if it's acceptable.

**Comment by seemethere** [comment]
Closed by #4
